### ISSUE TITLE
Cinnamon rolls burnt 🔥 

### ISSUE THREAD

**Issue by elletjies** [tobyhodges/baking-novice-20230419#3]
The temperature stated in the recipe (i.e. 290 C) is wrong! 375 F is 190 C.

**Comment by tobyhodges** [comment]
Thank you very much for reporting this - it does look like we made a mistake when converting the temperature to metric. Would you like to open a pull request to fix this?

**Comment by tobyhodges** [comment]
Oh, it looks like you already opened a pull request (#4) - thank you!
